name: "Lint"

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm

      - run: npm ci

      - name: Lint Format
        run: npx prettier --check .

      - name: Lint JS
        run: npm run lint:js -- --no-error-on-unmatched-pattern
